# Generated by Django 6.0.2 on 2026-02-21 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_remove_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmessage',
            name='email',
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
