# Generated by Django 6.0.2 on 2026-02-21 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_remove_contactmessage_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='carat',
            field=models.CharField(blank=True, help_text='e.g. 24K, 18K, VS1', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='weight_grams',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Weight in grams', max_digits=8, null=True),
        ),
    ]
