# Generated by Django 6.0.2 on 2026-02-22 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_product_carat_product_weight_grams'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['-is_primary', 'id']},
        ),
    ]
